### ISSUE TITLE
how to code difficulty-dependent drift rates

### ISSUE THREAD

**Issue by anne-urai** [kiante-fernandez/2023_choicehistory_HSSM#1]
either
- categorical coding for each stimulus difficulty level (e.g. `coherence` or `contrast`)
- assume a fixed sigmoid relationship

explored in https://github.com/anne-urai/mouse_history_ddm/blob/main/plot_contrast_rescale.py

**Comment by anne-urai** [comment]
in the eLife paper on human datasets, we used the `depends_on` syntax https://github.com/anne-urai/2019_Urai_choice-history-ddm/blob/master/hddm_models.py#L177

**Comment by anne-urai** [comment]
ask @AlexanderFengler: is it desirable to impose the constraint that increasing stimulus difficulty predicts a (monotonic, but not necessarily linear) increase in drift rate?

**Comment by AlexanderFengler** [comment]
In principle it is a reasonable constraint I would say. 
If this is violated, it may indicate a problem with the experimental design.

Having said that, in the regression framework, you can still just use dummy coding for stimulus difficulty, which imposes no constraints.

**Comment by anne-urai** [comment]
Let's go for dummy (treatment) coding then, and we can add the monotonic increase as a sanity check for each mouse's fit

**Comment by anne-urai** [comment]
Make plot as above: drift rate per coherence level
