### ISSUE TITLE
readme instructions

### ISSUE THREAD

**Issue by anne-urai** [kiante-fernandez/2023_choicehistory_HSSM#7]

**Comment by anne-urai** [comment]
- [ ] how to install HSSM (github vs pypi) @anne-urai  and stay up to date during this project
- [ ] how to stay up to date with this repo @kiante-fernandez 
- [ ] how to change and contribute code @kiante-fernandez

**Comment by AlexanderFengler** [comment]
will take care of this by the end of the week.

**Comment by AlexanderFengler** [comment]
Made an example pull request @Zeynepgnezkan @anne-urai @kiante-fernandez  and requested everyone as reviewers, just to go through the motions of this once. 

In this pull request I put some initial content in the readme concerning contribution to the repo.
